# Generated by Django 4.1.7 on 2023-02-28 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iid', '0002_alter_segment_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
    ]
