# Generated by Django 4.1.7 on 2023-02-28 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
        ('iid', '0003_subsegment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Iid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('objective', models.TextField()),
                ('tagcc_date', models.DateField()),
                ('itc_date', models.DateField()),
                ('go_live_date', models.DateField()),
                ('application_l3', models.ManyToManyField(related_name='iid_application_l3', to='employee.employee')),
                ('lead_technical_delivery_manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='iid_lead_tech_delivery_mgr', to='employee.employee')),
                ('project_managers', models.ManyToManyField(related_name='iid_project_managers', to='employee.employee')),
                ('security_architect', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='iid_security_architect', to='employee.employee')),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='iid.segment')),
                ('steering_committee_members', models.ManyToManyField(related_name='iid_steering_committee_members', to='employee.employee')),
                ('subsegment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='iid.subsegment')),
                ('to_head', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='iid_to_head', to='employee.employee')),
            ],
        ),
    ]
