# Generated by Django 4.1.7 on 2023-02-28 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
        ('iid', '0004_iid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iid',
            name='to_head',
        ),
        migrations.AddField(
            model_name='iid',
            name='tno_head',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='iid_tno_head', to='employee.employee'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='iid',
            name='application_l3',
        ),
        migrations.AddField(
            model_name='iid',
            name='application_l3',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='iid_application_l3', to='employee.employee'),
            preserve_default=False,
        ),
    ]
