# Generated by Django 4.1.7 on 2023-02-28 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
        ('iid', '0005_remove_iid_to_head_iid_tno_head_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='iid',
            name='requestor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='iid_requestor', to='employee.employee'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='iid',
            name='watchers',
            field=models.ManyToManyField(related_name='iid_watchers', to='employee.employee'),
        ),
    ]
