# Generated by Django 4.1.7 on 2023-03-01 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
        ('iid', '0008_iid_fsm_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iid',
            name='approver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='iid_approver', to='employee.employee'),
        ),
        migrations.AlterField(
            model_name='iid',
            name='requestor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='iid_requestor', to='employee.employee'),
        ),
        migrations.AlterField(
            model_name='iid',
            name='reviewer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='iid_reviewer', to='employee.employee'),
        ),
        migrations.AlterField(
            model_name='iid',
            name='verifier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='iid_verifier', to='employee.employee'),
        ),
        migrations.AlterField(
            model_name='iid',
            name='watchers',
            field=models.ManyToManyField(null=True, related_name='iid_watchers', to='employee.employee'),
        ),
    ]
