# Generated by Django 4.1.7 on 2023-03-01 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
        ('iid', '0010_alter_segment_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iid',
            name='watchers',
            field=models.ManyToManyField(related_name='iid_watchers', to='employee.employee'),
        ),
    ]
