# Generated by Django 4.1.7 on 2023-05-12 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='BigFix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='BigFixConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_big_fix_required', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='BigFixCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=255)),
                ('config', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='VMwareServerSizeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vmware_server_cpu', models.IntegerField()),
                ('vmware_server_ram', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='VMwareServerSizeCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=255)),
                ('config', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost_type', models.CharField(max_length=50)),
                ('vmware_server_size_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vmware_server.vmwareserversizeconfig')),
            ],
        ),
        migrations.CreateModel(
            name='VMwareServerRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.IntegerField()),
                ('bom', models.IntegerField()),
                ('requestor', models.CharField(max_length=100)),
                ('environment', models.CharField(max_length=100)),
                ('layer', models.CharField(max_length=100)),
                ('hostname', models.CharField(max_length=255)),
                ('platform', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('clustering', models.BooleanField()),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vmware_server.application')),
                ('big_fix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vmware_server.bigfix')),
            ],
        ),
        migrations.AddField(
            model_name='bigfix',
            name='big_fix_config',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='vmware_server.bigfixconfig'),
        ),
        migrations.AddField(
            model_name='bigfix',
            name='big_fix_cost',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='vmware_server.bigfixcost'),
        ),
    ]
