# Generated by Django 4.1.7 on 2023-05-12 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vmware_server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BigFixNew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('big_fix_config', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='vmware_server.bigfixconfig')),
                ('big_fix_cost', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='vmware_server.bigfixcost')),
            ],
        ),
        migrations.AlterField(
            model_name='vmwareserverrecord',
            name='big_fix',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vmware_server.bigfixnew'),
        ),
    ]
