# Generated by Django 4.1.7 on 2023-05-12 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vmware_server', '0003_alter_vmwareserverrecord_big_fix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vmwareserversizecost',
            name='cost_type',
        ),
        migrations.RemoveField(
            model_name='vmwareserversizecost',
            name='vmware_server_size_config',
        ),
        migrations.AddField(
            model_name='vmwareserversizecost',
            name='type',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='VMwareServerSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vmware_server_size_config', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='vmware_server.vmwareserversizeconfig')),
                ('vmware_server_size_cost', models.ManyToManyField(to='vmware_server.vmwareserversizecost')),
            ],
        ),
    ]
