# Generated by Django 4.1.7 on 2023-05-12 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vmware_server', '0004_remove_vmwareserversizecost_cost_type_and_more'),
    ]

    operations = [
    ]
