# Generated by Django 4.1.7 on 2023-05-13 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billofmaterial', '0006_billofmaterial_project'),
        ('infrastructureinitiationdocument', '0014_alter_iidrequestor_requestor'),
        ('vmware_server', '0006_vmwareserverrecord_vmware_server_size_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VmwareServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requestor', models.CharField(max_length=100)),
                ('environment', models.CharField(max_length=100)),
                ('layer', models.CharField(max_length=100)),
                ('hostname', models.CharField(max_length=100)),
                ('platform', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('clustering', models.CharField(max_length=100)),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billofmaterial.billofmaterial')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infrastructureinitiationdocument.iidproject')),
            ],
        ),
        migrations.RemoveField(
            model_name='bigfixnew',
            name='big_fix_config',
        ),
        migrations.RemoveField(
            model_name='bigfixnew',
            name='big_fix_cost',
        ),
        migrations.RemoveField(
            model_name='vmwareserverrecord',
            name='application',
        ),
        migrations.RemoveField(
            model_name='vmwareserverrecord',
            name='big_fix',
        ),
        migrations.RemoveField(
            model_name='vmwareserverrecord',
            name='vmware_server_size',
        ),
        migrations.RemoveField(
            model_name='vmwareserversize',
            name='vmware_server_size_config',
        ),
        migrations.RemoveField(
            model_name='vmwareserversize',
            name='vmware_server_size_cost',
        ),
        migrations.RemoveField(
            model_name='vmwareserversizecost',
            name='type',
        ),
        migrations.AddField(
            model_name='bigfixcost',
            name='big_fix_config',
            field=models.ForeignKey( on_delete=django.db.models.deletion.CASCADE, to='vmware_server.bigfixconfig', null=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vmwareserversizecost',
            name='cost_type',
            field=models.CharField( max_length=100,null=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vmwareserversizecost',
            name='vmware_server_size_config',
            field=models.ForeignKey( on_delete=django.db.models.deletion.CASCADE, to='vmware_server.vmwareserversizeconfig',null=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='code',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='application',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bigfixcost',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bigfixcost',
            name='config',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bigfixcost',
            name='cost_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bigfixcost',
            name='item',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vmwareserversizecost',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vmwareserversizecost',
            name='config',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vmwareserversizecost',
            name='item',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='BigFix',
        ),
        migrations.DeleteModel(
            name='BigFixNew',
        ),
        migrations.DeleteModel(
            name='VMwareServerRecord',
        ),
        migrations.DeleteModel(
            name='VMwareServerSize',
        ),
        migrations.AddField(
            model_name='application',
            name='vmware_server',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='vmware_server.vmwareserver'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bigfixconfig',
            name='vmware_server',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='vmware_server.vmwareserver'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vmwareserversizeconfig',
            name='vmware_server',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='vmware_server.vmwareserver'),
            preserve_default=False,
        ),
    ]
