# Generated by Django 4.1.7 on 2023-05-13 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmware_server', '0007_vmwareserver_remove_bigfixnew_big_fix_config_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vmwareserversizecost',
            name='cost_type',
            field=models.CharField(max_length=100),
        ),
    ]
