# Generated by Django 4.1.7 on 2023-05-13 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vmware_server', '0009_remove_application_vmware_server_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vmwareserversizeconfig',
            name='vmware_server',
        ),
        migrations.RemoveField(
            model_name='vmwareserversizecost',
            name='vmware_server_size_config',
        ),
        migrations.CreateModel(
            name='VmwareServerSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vmware_server_size_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vmware_server_sizes', to='vmware_server.vmwareserversizeconfig')),
                ('vmware_server_size_cost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vmware_server_sizes', to='vmware_server.vmwareserversizecost')),
            ],
        ),
        migrations.AddField(
            model_name='vmwareserver',
            name='vmmware_server_size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vmware_servers', to='vmware_server.vmwareserversize'),
            preserve_default=False,
        ),
    ]
