# Generated by Django 4.1.7 on 2023-05-13 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmware_server', '0011_alter_vmwareserver_big_fix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vmwareserversize',
            name='vmware_server_size_cost',
        ),
        migrations.AddField(
            model_name='vmwareserversize',
            name='vmware_server_size_cost',
            field=models.ManyToManyField(related_name='vmware_server_sizes', to='vmware_server.vmwareserversizecost'),
        ),
    ]
