# Generated by Django 4.1.7 on 2023-05-13 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vmware_server', '0013_remove_vmwareserver_big_fix_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vmwareserver',
            old_name='vmmware_server_size_config',
            new_name='vmware_server_size_config',
        ),
        migrations.RenameField(
            model_name='vmwareserver',
            old_name='vmmware_server_size_cost',
            new_name='vmware_server_size_cost',
        ),
    ]
