# Generated by Django 4.1.7 on 2023-05-14 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vmware_server', '0014_rename_vmmware_server_size_config_vmwareserver_vmware_server_size_config_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vmwareserversize',
            name='vmware_server_size_config',
        ),
        migrations.RemoveField(
            model_name='vmwareserversize',
            name='vmware_server_size_cost',
        ),
        migrations.RemoveField(
            model_name='vmwareserver',
            name='big_fix_config',
        ),
        migrations.RemoveField(
            model_name='vmwareserver',
            name='big_fix_cost',
        ),
        migrations.RemoveField(
            model_name='vmwareserver',
            name='vmware_server_size_config',
        ),
        migrations.RemoveField(
            model_name='vmwareserver',
            name='vmware_server_size_cost',
        ),
        migrations.AddField(
            model_name='application',
            name='vmware_server',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='vmware_server.vmwareserver'),
        ),
        migrations.AddField(
            model_name='bigfixconfig',
            name='vmware_server',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='big_fix_configs', to='vmware_server.vmwareserver'),
        ),
        migrations.AddField(
            model_name='bigfixcost',
            name='vmware_server',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='big_fix_costs', to='vmware_server.vmwareserver'),
        ),
        migrations.AddField(
            model_name='vmwareserversizeconfig',
            name='vmware_server',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vmware_server_size_configs', to='vmware_server.vmwareserver'),
        ),
        migrations.AddField(
            model_name='vmwareserversizecost',
            name='vmware_server',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vmware_server_size_costs', to='vmware_server.vmwareserver'),
        ),
        migrations.DeleteModel(
            name='BigFix',
        ),
        migrations.DeleteModel(
            name='VmwareServerSize',
        ),
    ]
