# Generated by Django 4.1.7 on 2023-05-14 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vmware_server', '0015_remove_vmwareserversize_vmware_server_size_config_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vmwareserver',
            name='application',
        ),
    ]
