# Generated by Django 4.1.7 on 2023-05-14 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vmware_server', '0016_remove_vmwareserver_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bigfixconfig',
            name='vmware_server',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='big_fix_config', to='vmware_server.vmwareserver'),
        ),
    ]
