# Generated by Django 4.1.7 on 2023-04-22 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oracledb', '0002_oracledb_bom_component'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oracledb',
            name='bom_component',
        ),
    ]
