# Generated by Django 4.1.7 on 2023-03-05 11:02

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructureinitiationdocument', '0002_iidproject_fsm_state'),
    ]

    operations = [
        
    ]
