# Generated by Django 4.1.7 on 2023-03-07 05:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructureinitiationdocument', '0005_alter_iidrequestor_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iidrequestor',
            name='email',
            field=models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()]),
        ),
    ]
