# Generated by Django 4.1.7 on 2023-03-07 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructureinitiationdocument', '0010_alter_iidrequestor_requestor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iidrequestor',
            name='iid_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requestors', to='infrastructureinitiationdocument.iidproject'),
        ),
    ]
