# Generated by Django 4.1.7 on 2023-03-08 05:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('infrastructureinitiationdocument', '0013_alter_iidrequestor_iid_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iidrequestor',
            name='requestor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requestor_iid_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
