# Generated by Django 4.1.7 on 2023-03-30 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pricebook', '0004_historicalsku'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hypervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costs', models.ManyToManyField(to='pricebook.costtype')),
            ],
        ),
        migrations.CreateModel(
            name='OsStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField()),
                ('costs', models.ManyToManyField(to='pricebook.costtype')),
            ],
        ),
        migrations.CreateModel(
            name='VirtualMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
                ('vcpu', models.IntegerField()),
                ('ram_gb', models.IntegerField()),
                ('costs', models.ManyToManyField(to='pricebook.costtype')),
                ('hypervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricebook.hypervisor')),
                ('os_storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricebook.osstorage')),
            ],
        ),
    ]
