# Generated by Django 4.1.7 on 2023-04-12 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pricebook', '0009_remove_vmwareserversize_hypervisor_cost_ce_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualServerNetworkCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='network_cost_type', to='pricebook.costtype')),
                ('server_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network_cost_server_type', to='pricebook.servertype')),
            ],
        ),
        migrations.DeleteModel(
            name='NetworkCost',
        ),
    ]
