# Generated by Django 4.1.7 on 2023-04-12 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricebook', '0011_vmwareservercost_network_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vmwareservercost',
            name='network_cost',
        ),
    ]
