# Generated by Django 4.1.7 on 2023-04-12 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricebook', '0012_remove_vmwareservercost_network_cost'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VmwareServerCost',
            new_name='VirtualServerCost',
        ),
        migrations.RenameModel(
            old_name='VMwareServerSize',
            new_name='VirtualServerSize',
        ),
    ]
