# Generated by Django 4.1.7 on 2023-04-21 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pricebook', '0014_remove_osstorage_costs_remove_virtualmachine_costs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtualservercost',
            name='cost_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='virtual_server_cost_type', to='pricebook.costtype'),
        ),
        migrations.AlterField(
            model_name='virtualservercost',
            name='server_size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='virtual_server_cost', to='pricebook.virtualserversize'),
        ),
    ]
