# Generated by Django 4.1.7 on 2023-05-04 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricebook', '0015_alter_virtualservercost_cost_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SanStorageCompression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compression_ratio', models.FloatField()),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SanStorageOverhead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overhead_ratio', models.FloatField()),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SanStorageRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_to', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=255)),
            ],
        ),
    ]
