# Generated by Django 4.1.7 on 2023-05-05 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pricebook', '0017_backupnasstoragecostreductionmultiplier_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VmwareServerOperatingSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=255, unique=True)),
                ('code', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='VmwareServerOperatingSystemSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_size', models.PositiveIntegerField()),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricebook.vmwareserveroperatingsystem')),
            ],
        ),
    ]
