# Generated by Django 4.1.7 on 2023-05-05 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pricebook', '0018_vmwareserveroperatingsystem_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VmwareServerOperatingSystemSize',
            new_name='VmwareServerOperatingSystemStorageSize',
        ),
        migrations.CreateModel(
            name='VmwareServerOperatingSystemPriceBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(max_length=255)),
                ('cost_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricebook.costtype')),
                ('os', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='price_book', to='pricebook.vmwareserveroperatingsystem')),
            ],
        ),
    ]
