# Generated by Django 4.1.7 on 2023-05-06 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pricebook', '0020_sanstoragetype_sanstoragepricebook'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupStorageType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='BackupStoragePriceBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(max_length=255)),
                ('cost_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricebook.costtype')),
                ('storage_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='price_book', to='pricebook.backupstoragetype')),
            ],
        ),
    ]
