# Generated by Django 4.1.7 on 2023-05-07 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pricebook', '0021_backupstoragetype_backupstoragepricebook'),
    ]

    operations = [
        migrations.CreateModel(
            name='VmwareServerSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=250)),
                ('vcpu', models.IntegerField()),
                ('ram_gb', models.IntegerField()),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='VmwareServerPricebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=250)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(max_length=255)),
                ('cost_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricebook.costtype')),
            ],
        ),
    ]
