# Generated by Django 4.1.7 on 2023-03-01 08:00

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='fsm_state',
            field=django_fsm.FSMField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=50),
        ),
    ]
