# Generated by Django 4.1.7 on 2023-03-01 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
        ('project', '0002_project_fsm_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects_approved', to='employee.employee'),
        ),
        migrations.AlterField(
            model_name='project',
            name='verifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects_verified', to='employee.employee'),
        ),
    ]
