# Generated by Django 4.1.7 on 2023-05-23 06:07

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_project_approver_alter_project_verifier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='approver',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_managers',
        ),
        migrations.RemoveField(
            model_name='project',
            name='requestor',
        ),
        migrations.RemoveField(
            model_name='project',
            name='verifier',
        ),
        migrations.AddField(
            model_name='project',
            name='description_objective',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='fsm_state',
            field=django_fsm.FSMField(choices=[('Draft', 'Draft'), ('Review', 'Review'), ('Submitted', 'Submitted'), ('Verified', 'Verified'), ('Approved', 'Approved'), ('Cancelled', 'Cancelled'), ('Rework', 'Rework'), ('Resubmitted', 'Resubmitted'), ('Rereviewed', 'Rereviewed')], default='Draft', max_length=50, protected=True),
        ),
    ]
