# Generated by Django 4.1.7 on 2023-05-24 06:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0006_projectaction_delete_projectrequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectaction',
            options={},
        ),
        migrations.RenameField(
            model_name='projectaction',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='project',
            name='fsm_state',
            field=django_fsm.FSMField(choices=[('ProjectDraft', 'Project Draft'), ('ProjectReviewed', 'Project Reviewed'), ('ProjectSubmitted', 'Project Submitted'), ('ProjectVerified', 'Project Verified'), ('ProjectApproved', 'Project Approved'), ('ProjectCancelled', 'Project Cancelled'), ('ProjectReworked', 'Project Reworked'), ('ProjectReworkSubmitted', 'Project Rework Submitted'), ('ProjectReworkReviewed', 'Project Rework Reviewed')], default='ProjectDraft', max_length=50, protected=True),
        ),
        migrations.AlterField(
            model_name='projectaction',
            name='action',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='projectaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
