# Generated by Django 4.1.7 on 2023-05-24 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_alter_projectaction_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectaction',
            old_name='created_at',
            new_name='timestamp',
        ),
        migrations.AlterField(
            model_name='projectaction',
            name='action',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='projectaction',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project'),
        ),
    ]
