# Generated by Django 4.1.7 on 2023-05-24 07:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0002_rename_role_userrole_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0008_rename_created_at_projectaction_timestamp_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectRole',
            new_name='ProjectPermission',
        ),
    ]
