# Generated by Django 4.1.7 on 2023-05-24 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_rename_projectrole_projectpermission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpermission',
            name='role',
            field=models.CharField(max_length=255),
        ),
    ]
