# Generated by Django 4.1.7 on 2023-05-25 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_alter_projectpermission_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectaction',
            name='user',
        ),
        migrations.RemoveField(
            model_name='projectpermission',
            name='user',
        ),
        migrations.AddField(
            model_name='projectaction',
            name='email',
            field=models.EmailField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectaction',
            name='fullname',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectaction',
            name='username',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectpermission',
            name='email',
            field=models.EmailField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectpermission',
            name='fullname',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectpermission',
            name='username',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
