# Generated by Django 4.1.7 on 2023-04-21 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billofmaterial', '0002_billofmaterialcomponent'),
        ('infrastructureinitiationdocument', '0014_alter_iidrequestor_requestor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='OperatingSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Requestor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='VirtualServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('environment', models.CharField(max_length=255)),
                ('layer', models.CharField(max_length=255)),
                ('hostname', models.CharField(max_length=255)),
                ('platform', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('clustering', models.BooleanField()),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='virtual_server.application')),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billofmaterial.billofmaterial')),
                ('operating_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='virtual_server.operatingsystem')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infrastructureinitiationdocument.iidproject')),
                ('requestor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='virtual_server.requestor')),
            ],
        ),
        migrations.CreateModel(
            name='VirtualServerCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost_type', models.CharField(max_length=255)),
                ('virtual_server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costs', to='virtual_server.virtualserver')),
            ],
        ),
        migrations.CreateModel(
            name='VirtualServerConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
                ('vcpu', models.IntegerField()),
                ('ram_gb', models.IntegerField()),
                ('virtual_server', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuration', to='virtual_server.virtualserver')),
            ],
        ),
        migrations.CreateModel(
            name='OperatingSystemCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost_type', models.CharField(max_length=255)),
                ('operating_system', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cost', to='virtual_server.operatingsystem')),
            ],
        ),
    ]
