# Generated by Django 4.1.7 on 2023-04-21 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtual_server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtualserver',
            name='requestor',
            field=models.CharField(max_length=255),
        ),
    ]
