# Generated by Django 4.1.7 on 2023-04-21 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('virtual_server', '0002_alter_virtualserver_requestor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='virtualserver',
            name='clustering',
        ),
        migrations.RemoveField(
            model_name='virtualserver',
            name='hostname',
        ),
        migrations.RemoveField(
            model_name='virtualserver',
            name='model',
        ),
        migrations.RemoveField(
            model_name='virtualserver',
            name='operating_system',
        ),
        migrations.RemoveField(
            model_name='virtualserver',
            name='platform',
        ),
    ]
