# Generated by Django 4.1.7 on 2023-04-21 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('virtual_server', '0004_virtualserver_clustering_virtualserver_hostname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualserver',
            name='operating_system',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='virtual_server.operatingsystem'),
            preserve_default=False,
        ),
    ]
