# Generated by Django 4.1.7 on 2023-04-21 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('virtual_server', '0005_virtualserver_operating_system'),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualServerSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
                ('vcpu', models.IntegerField()),
                ('ram_gb', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='operatingsystemcost',
            name='operating_system',
        ),
        migrations.RemoveField(
            model_name='virtualservercost',
            name='virtual_server',
        ),
        migrations.AddField(
            model_name='operatingsystemcost',
            name='code',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='operatingsystemcost',
            name='description',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='operatingsystemcost',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='virtualserver',
            name='cost',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='virtual_server.virtualservercost'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='virtualserver',
            name='operating_system_cost',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='virtual_server.operatingsystemcost'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='VirtualServerConfiguration',
        ),
        migrations.AddField(
            model_name='virtualserver',
            name='size',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='virtual_server.virtualserversize'),
            preserve_default=False,
        ),
    ]
