# Generated by Django 4.1.7 on 2023-03-04 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billofmaterial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillOfMaterialComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('bill_of_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='billofmaterial.billofmaterial')),
            ],
        ),
    ]
