# Generated by Django 4.1.7 on 2023-04-22 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oracledb', '0003_remove_oracledb_bom_component'),
        ('billofmaterial', '0002_billofmaterialcomponent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BillOfMaterialComponent',
        ),
    ]
