# Generated by Django 4.1.7 on 2023-04-22 09:20

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('billofmaterial', '0003_delete_billofmaterialcomponent'),
    ]

    operations = [
        migrations.AddField(
            model_name='billofmaterial',
            name='status',
            field=django_fsm.FSMField(choices=[('requested', 'Requested'), ('reviewed', 'Reviewed'), ('revision', 'Revision'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='requested', max_length=50),
        ),
    ]
