# Generated by Django 4.1.7 on 2023-04-22 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billofmaterial', '0004_billofmaterial_status'),
    ]

    operations = [
    ]
