# Generated by Django 4.1.7 on 2023-04-22 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructureinitiationdocument', '0014_alter_iidrequestor_requestor'),
        ('billofmaterial', '0005_auto_20230422_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='billofmaterial',
            name='project',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='boms', to='infrastructureinitiationdocument.iidproject'),
            preserve_default=False,
        ),
    ]
