# Generated by Django 4.1.7 on 2023-03-02 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
       
    ]

    operations = [
        
    ]
