# Generated by Django 4.1.7 on 2023-03-03 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenSystemsIntelVirtualServerConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('environment', models.CharField(max_length=255)),
                ('layer', models.CharField(max_length=255)),
                ('server_details', models.CharField(max_length=255)),
                ('cpu_count', models.IntegerField()),
                ('memory_gb', models.DecimalField(decimal_places=2, max_digits=10)),
                ('os_version', models.CharField(max_length=255)),
                ('platform', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('network_port_count', models.IntegerField()),
                ('bom_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='virtual_server_configuration', to='bom.bomitem')),
            ],
        ),
        migrations.CreateModel(
            name='VirtualServerSoftwarePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ibm_pvu_count_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tem_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hypervisor_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('red_hat_os_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('configuration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='software_price', to='bom.opensystemsintelvirtualserverconfiguration')),
            ],
        ),
        migrations.CreateModel(
            name='VirtualServerHardwarePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hardware_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ram_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('storage_san_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('backup_san_storage_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nas_storage_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('san_port_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('network_port_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('configuration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hardware_price', to='bom.opensystemsintelvirtualserverconfiguration')),
            ],
        ),
    ]
