# Generated by Django 4.1.7 on 2023-03-09 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_customuser_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customgroup',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customgroup',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
